# Generated by Django 5.2 on 2025-04-30 10:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safecircles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='safecirclepost',
            options={'ordering': ['-is_pinned', '-is_urgent', '-created_at']},
        ),
        migrations.AddField(
            model_name='safecircle',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether the SafeCircle is visible to non-members'),
        ),
        migrations.AddField(
            model_name='safecircle',
            name='join_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='safecircle',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='safecircle',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='safecircle',
            name='radius',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Radius in kilometers', max_digits=5),
        ),
        migrations.AddField(
            model_name='safecirclemembership',
            name='last_check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='safecirclepost',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='safecirclepost',
            name='post_type',
            field=models.CharField(choices=[('announcement', 'Announcement'), ('alert', 'Alert'), ('update', 'Update'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('safe', 'Safe'), ('concerned', 'Concerned'), ('emergency', 'Emergency')], default='safe', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='safecircles.safecirclemembership')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='active', max_length=20)),
                ('report_type', models.CharField(choices=[('emergency', 'Emergency'), ('suspicious', 'Suspicious Activity'), ('general', 'General')], default='general', max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location_description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='safecircles.report')),
            ],
        ),
        migrations.CreateModel(
            name='ReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='report_photos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='safecircles.report')),
            ],
        ),
    ]
